---
openapi: 3.0.0
info:
  title: Nimble Survey API Documentation
  description: This is the API documentation for Nimble Survey
  version: 1.0.0

servers:
  - url: https://survey-api-staging.nimblehq.co/api/v1
    description: Staging server
  - url: https://survey-api.nimblehq.co/api/v1
    description: Production server

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

paths:
  /oauth/token:
    $ref: "paths/oauth/post_login_email.yml"
