---
openapi: 3.0.0
info:
  title: Nimble Survey API Documentation
  description: This is the API documentation for Nimble Survey
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: Local server

  - url: https://survey-api-staging.nimblehq.co/api/v1
    description: Staging server

  - url: https://survey-api.nimblehq.co/api/v1
    description: Production server

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants read and write access to administrative information
  schemas:
    #### REQUESTS ####
    requests_oauth_post_login_email:
      $ref: "requests/oauth/post_login_email.yml"

    #### RESPONSES ####
    responses_oauth_post_login_email:
      $ref: "responses/oauth/post_login_email.yml"

    #### REUSABLE SCHEMAS ####
    token:
      $ref: "schemas/token.yml"
    survey:
      $ref: "schemas/survey.yml"

paths:
  /oauth/token:
    $ref: "paths/oauth/post_login_email.yml"
