---
openapi: 3.0.0
info:
  title: Nimble Survey API Documentation
  description: This is the API documentation for Nimble Survey
  version: 1.0.0

servers:
  - url: '{base_url}'
    variables:
      base_url:
        default: survey-api.nimblehq.co     # Production server
        enum:
          - http://localhost:3000                       # Development server
          - http://localhost:4010                       # Mock Development server
          - https://survey-api-staging.nimblehq.co      # Staging server
          - https://survey-api-staging.nimblehq.co:4010 # Mock Staging server
          - https://survey-api.nimblehq.co              # Production server

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

paths:
  /api/v1/oauth/token:
    $ref: "paths/oauth/post_login_email.yml"
