---
openapi: 3.0.0
info:
  title: Nimble Survey API Documentation
  description: This is the API documentation for Nimble Survey
  version: 1.0.0

servers:
  - url: https://survey-api-staging.nimblehq.co/api/v1
    description: Staging server
  - url: https://survey-api.nimblehq.co/api/v1
    description: Production server

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    $ref: "schemas.yml"
  responses:
    $ref: "responses.yml"

paths:
  /registrations:
    $ref: "paths/registrations.yml"

  /oauth/token:
    $ref: "paths/oauth/token.yml"

  /oauth/revoke:
    $ref: "paths/oauth/revoke.yml"

  /surveys:
    $ref: "paths/surveys.yml"

tags:
  - name: Authentication
    description: Authentication APIs
  - name: Surveys
    description: Survey APIs
