extends: stylelint-config-standard
plugins:
  - stylelint-order
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - tailwind
      - apply
      - variants
      - responsive
      - screen
      - function
      - each
      - if
      - else
      - return
  declaration-block-trailing-semicolon: null
  no-descending-specificity: null
