version: '3.2'

services:
  db:
    image: postgres:12.1
    container_name: nimble_survey_web_db
    environment:
      - POSTGRES_DB=nimble_survey_web_development
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.7
    container_name: nimble_survey_web_redis
    ports:
      - "6379:6379"
