version: '3.2'

services:
  db:
    image: postgres:15.2
    container_name: nimble_survey_web_db
    environment:
      - POSTGRES_DB=nimble_survey_web_test
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"

  redis:
    image: redis:7.0
    container_name: nimble_survey_web_db
    ports:
      - "6379"

  test:
    build:
      context: .
      cache_from:
        - ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${BRANCH_TAG}-test
      args:
        - BUILD_ENV=test
        - RUBY_ENV=test
        - NODE_ENV=test
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${BRANCH_TAG}-test
    container_name: nimble_survey_web_test
    command: bin/test.sh
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - "ruby-bundle:/bundle"
      - "${PWD}/tmp/screenshots:/nimble_survey_web/tmp/screenshots"
      - "${PWD}/log:/nimble_survey_web/log"
    environment:
      - RACK_ENV=test
      - RAILS_ENV=test
      - NODE_ENV=test
      - DB_HOST=db
      - CI=$CI
      - TEST_RETRY=$TEST_RETRY
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  ruby-bundle:
