version: '3.2'

services:
  db:
    image: postgres:12.1
    container_name: nimble_survey_web_db
    environment:
      - POSTGRES_DB=nimble_survey_web_test
    ports:
      - "5432"

  redis:
    image: redis:5.0.7
    container_name: nimble_survey_web_redis
    ports:
      - "6379"

  test:
    build:
      context: .
      cache_from:
        - ${DOCKER_IMAGE}:${BRANCH_TAG}
      args:
        - BUILD_ENV=test
        - RUBY_ENV=test
        - NODE_ENV=test
    image: ${DOCKER_IMAGE}:${BRANCH_TAG}
    container_name: nimble_survey_web_test
    command: bin/test.sh
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - "ruby-bundle:/bundle"
      - "${PWD}/tmp/screenshots:/nimble_survey_web/tmp/screenshots"
      - "${PWD}/log:/nimble_survey_web/log"
    environment:
      - RACK_ENV=test
      - RAILS_ENV=test
      - NODE_ENV=test
      - DB_HOST=db
      - CI=$CI
      - TEST_RETRY=$TEST_RETRY

volumes:
  ruby-bundle:
