openapi: 3.0.0
info:
  title: Nimble Survey API Documentation
  description: This is the API documentation for Nimble Survey
  version: 1.0.0
servers:
  - url: 'https://survey-api-staging.nimblehq.co/api/v1'
    description: Staging server
  - url: 'https://survey-api.nimblehq.co/api/v1'
    description: Production server
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    requests_oauth_post_login_email:
      type: object
      description: A request body for a new OAuth 2.0 token
      required:
        - grant_type
        - email
        - password
        - client_id
        - client_secret
      properties:
        grant_type:
          type: string
          example: password
          description: |-
            The type of request being made, either using a client-side obtained
            authorization code, a refresh token, a JWT assertion, client credentials
            grant or another access token for the purpose of downscoping a token. In this API, please use `password`
        email:
          type: string
          description: |-
            The email of the user requesting an access token.

            Used in combination with `password` as the `grant_type`.
          example: dev@example.com
        password:
          type: string
          description: |-
            The password of the user requesting an access token.

            Used in combination with `password` as the `grant_type`.
          example: password
        client_id:
          type: string
          description: |-
            The Client ID of the application requesting an access token.

            Used in combination with `password` as the `grant_type`.
          example: ly1nj6n11vionaie65emwzk575hnnmrk
        client_secret:
          type: string
          description: |-
            The client secret of the application requesting an access token.

            Used in combination with `password` as the `grant_type`.
          example: hOzsTeFlT6ko0dme22uGbQal04SBPYc1
    responses_oauth_post_login_email:
      type: object
      description: A response body for a new OAuth 2.0 token
      properties:
        data:
          type: object
          description: The data object
          properties:
            id:
              type: string
              description: The identifier of the access token
              example: '123'
            type:
              type: string
              description: The type of the access token
              example: token
            attributes:
              $ref: '#/components/schemas/token'
    responses_surveys_get_survey_list:
      type: object
      description: A response body for a new OAuth 2.0 token
      properties:
        data:
          type: array
          description: The data array that contains a list of survey object
          maxItems: 10
          items:
            type: object
            properties:
              id:
                type: string
              type:
                type: string
              attributes:
                $ref: '#/components/schemas/survey'
        meta:
          type: object
          properties:
            page:
              type: number
              example: 1
            pages:
              type: number
              example: 10
            page_size:
              type: number
              example: 2
            records:
              type: number
              example: 20
    error:
      type: object
      properties:
        errors:
          type: array
          maxItems: 10
          items:
            type: object
            properties:
              code:
                type: string
                description: an application-specific error code
              detail:
                type: string
                description: 'a human-readable explanation specific to this occurrence of the problem. Like title, this field''s value can be localized.'
    token:
      type: object
      description: A request for a new OAuth 2.0 token
      properties:
        access_token:
          type: string
          description: The access token
        token_type:
          type: string
          description: The token type
        expires_in:
          type: integer
          description: The token expiry time in seconds
        refresh_token:
          type: string
          description: The refresh token
        created_at:
          type: integer
          description: The token creation time in seconds
      example:
        access_token: 123-f2i0CG6MDsf-wJE9FyYrhSGAOtxBkhYWDI
        token_type: Bearer
        expires_in: 7200
        refresh_token: l27GNT0kmkPbnEaUxniXyu4cHfPyWFr00kZTX5oWKA6c
        created_at: 1681974651
    survey:
      type: object
      description: A survey object
      properties:
        title:
          type: string
          description: The title of the survey
        description:
          type: string
          description: The description of the survey
        thank_email_above_threshold:
          type: string
          description: The thank you email above threshold
        thank_email_below_threshold:
          type: string
          description: The thank you email below threshold
        is_active:
          type: boolean
          description: The status of the survey
        cover_image_url:
          type: string
          description: The cover image url of the survey
        created_at:
          type: string
          description: The creation time of the survey
        active_at:
          type: string
          description: The active time of the survey
          nullable: true
        inactive_at:
          type: string
          description: The inactive time of the survey
          nullable: true
        survey_type:
          type: string
          description: The type of the survey
paths:
  /oauth/token:
    post:
      tags:
        - Authentication
      security: []
      summary: Login with email
      description: |-
        Request an Access Token using either a client-side obtained OAuth 2.0
        authorization code or a server-side JWT assertion.

        You will then send this code to this endpoint to exchange it for
        an Access Token. The returned Access Token can then be used to to make
        Survey API calls.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requests_oauth_post_login_email'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses_oauth_post_login_email'
        default:
          description: Error
          content:
            application/json:
              example:
                errors:
                  - code: invalid_request
                    detail: 'The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.'
              schema:
                $ref: '#/components/schemas/error'
  /surveys:
    get:
      tags:
        - Surveys
      security:
        - BearerAuth: []
      summary: Get the survey list
      description: Call this API to get the data of a list of survey
      parameters:
        - in: query
          name: 'page[number]'
          schema:
            type: integer
          description: The page number of the survey list.
          example: 1
        - in: query
          name: 'page[size]'
          schema:
            type: integer
          description: The page size of the survey list that client side expects to get.
          example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responses_surveys_get_survey_list'
              examples:
                bangkok:
                  value:
                    data:
                      - title: Scarlett Bangkok
                        description: We'd love ot hear from you!
                        thank_email_above_threshold: '<span style=font-family:arialhelveticasans-serif><span style=font-size:14px>Dear name<br /><br />Thank you for visiting Scarlett Wine Bar &amp; Restaurant at Pullman Bangkok Hotel G &nbsp;and for taking the time to complete our guest feedback survey!<br /><br />Your feedback is very important to us and each survey is read individually by the management and owners shortly after it is sent. We discuss comments and suggestions at our daily meetings and use them to constantly improve our services.<br /><br />We would very much appreciate it if you could take a few more moments and review us on TripAdvisor regarding your recent visit. By <a href=https://www.tripadvisor.com/Restaurant_Review-g293916-d2629404-Reviews-Scarlett_Wine_Bar_Restaurant-Bangkok.html>clicking here</a> you will be directed to our page.&nbsp;<br /><br />Thank you once again and we look forward to seeing you soon!<br /><br />The Team at Scarlett Wine Bar &amp; Restaurant&nbsp;</span></span><span style=font-family:arialhelveticasans-serif; font-size:14px>Pullman Bangkok Hotel G</span>'
                        thank_email_below_threshold: '<span style=font-size:14px><span style=font-family:arialhelveticasans-serif>Dear name<br /><br />Thank you for visiting&nbsp;</span></span><span style=font-family:arialhelveticasans-serif; font-size:14px>Uno Mas at Centara Central World&nbsp;</span><span style=font-size:14px><span style=font-family:arialhelveticasans-serif>&nbsp;and for taking the time to complete our customer&nbsp;feedback survey.</span></span><br /><br /><span style=font-family:arialhelveticasans-serif; font-size:14px>The Team at&nbsp;</span><span style=font-family:arialhelveticasans-serif><span style=font-size:14px>Scarlett Wine Bar &amp; Restaurant&nbsp;</span></span><span style=font-family:arialhelveticasans-serif; font-size:14px>Pullman Bangkok Hotel G</span>'
                        is_active: true
                        cover_image_url: 'https://dhdbhh0jsld0o.cloudfront.net/m/1ea51560991bcb7d00d0_'
                        created_at: '2017-01-23T07:48:12.991Z'
                        active_at: '2018-10-08T07:04:00.000Z'
                        inactive_at: '2019-10-08T07:04:00.000Z'
                        survey_type: Restaurant
                    meta:
                      page: 1
                      pages: 1
                      page_size: 1
                      records: 1
                riverside:
                  value:
                    data:
                      - title: ibis Bangkok Riverside
                        description: We'd love to hear from you!
                        thank_email_above_threshold: '<span style=font-family:arialhelveticasans-serif><span style=font-size:14px>Dear name<br /><br />Thank you for visiting Beach Republic and for taking the time to complete our brief survey. We are thrilled that you enjoyed your time with us! If you have a moment, we would be greatly appreciate it if you could leave a short review on <a href=http://www.tripadvisor.com/Hotel_Review-g1188000-d624070-Reviews-Beach_Republic_The_Residences-Lamai_Beach_Maret_Ko_Samui_Surat_Thani_Province.html>TripAdvisor</a>. It helps to spread the word and let others know about the Beach Republic Revolution!<br /><br />Thank you again and we look forward to welcoming you back soon.<br /><br />Sincerely,<br /><br />Beach Republic Team</span></span>'
                        thank_email_below_threshold: '<span style=font-family:arialhelveticasans-serif><span style=font-size:14px>Dear name<br /><br />Thank you for visiting Beach Republic and for taking the time to complete our brief survey. We are constantly striving to improve and your feedback allows us to help improve the experience for you on your next visit. Each survey is read individually by senior staff and discussed with the team in daily meetings.&nbsp;<br /><br />Thank you again and we look forward to welcoming you back soon.<br /><br />Sincerely,<br /><br />Beach Republic Team</span></span>'
                        is_active: true
                        cover_image_url: 'https://dhdbhh0jsld0o.cloudfront.net/m/287db81c5e4242412cc0_'
                        created_at: '2017-01-23T03:32:24.585Z'
                        active_at: '2016-01-22T04:12:00.000Z'
                        inactive_at: null
                        survey_type: Hotel
                    meta:
                      page: 1
                      pages: 1
                      page_size: 1
                      records: 1
        default:
          description: Error
          content:
            application/json:
              example:
                errors:
                  - code: invalid_request
                    detail: 'The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.'
              schema:
                $ref: '#/components/schemas/error'
tags:
  - name: Authentication
    description: Authentication APIs
  - name: Surveys
    description: Survey APIs
