default: &default
  BASIC_AUTHENTICATION_PASSWORD: "password"
  BASIC_AUTHENTICATION_USERNAME: "username"
  DB_NAME: "nimble_survey_web"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  MAILER_DEFAULT_HOST: "localhost"
  MAILER_DEFAULT_PORT: "3000"
  MAILER_SENDER: "Test <noreply@nimblehq.co>"
  APP_DOMAIN: "localhost"

development:
  <<: *default

test:
  <<: *default
  TEST_RETRY: "0"
