name: CI

on: push

env:
  DOCKER_HUB_USERNAME: ${{ github.repository_owner }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  COMPOSE_FILE: docker-compose.test.yml
  DOCKER_IMAGE: ${{ github.repository }}

jobs:
  export_branch_tag:
    name: Export branch tag
    runs-on: ubuntu-latest
    steps:
      - name: Set outputs
        id: export_branch_tag
        run: |
          export BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "##[set-output name=branch_tag;]$(echo ${BRANCH_NAME/\//-})"
    outputs:
      branch_tag: ${{ steps.export_branch_tag.outputs.branch_tag }}

  build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: export_branch_tag
    env:
      BRANCH_TAG: ${{ needs.export_branch_tag.outputs.branch_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo "$DOCKER_HUB_TOKEN" | docker login --username=$DOCKER_HUB_USERNAME --password-stdin
      - name: Docker pull
        if: env.BRANCH_TAG != 'master' && env.BRANCH_TAG != 'development'
        run: docker-compose pull test
      - name: Docker build
        run: |
          bin/docker-prepare
          docker-compose build
          docker-compose push test

  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: [export_branch_tag, build]
    env:
      BRANCH_TAG: ${{ needs.export_branch_tag.outputs.branch_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo "$DOCKER_HUB_TOKEN" | docker login --username=$DOCKER_HUB_USERNAME --password-stdin
      - name: Docker pull
        run: docker-compose pull
      - name: Linters
        run: docker-compose run test yarn lint
      - name: RSpec
        run: docker-compose run test bundle exec rspec --exclude-pattern "spec/systems/**/*_spec.rb" --profile

  system_test:
    name: System test
    runs-on: ubuntu-latest
    needs: [export_branch_tag, build]
    env:
      BRANCH_TAG: ${{ needs.export_branch_tag.outputs.branch_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo "$DOCKER_HUB_TOKEN" | docker login --username=$DOCKER_HUB_USERNAME --password-stdin
      - name: Docker pull
        run: docker-compose pull
      - name: RSpec
        run: docker-compose run test bundle exec rspec spec/systems --profile

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: [export_branch_tag, unit_test, system_test]
    env:
      BRANCH_TAG: ${{ needs.export_branch_tag.outputs.branch_tag }}
    if: needs.export_branch_tag.outputs.branch_tag.BRANCH_TAG == 'master' || needs.export_branch_tag.outputs.branch_tag.BRANCH_TAG == 'development'
    steps:
      - name: Invoke deployment workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deployment
          token: ${{ secrets.PERSONAL_TOKEN }}
