name: Danger

on: pull_request

jobs:
  danger:
    name: Run danger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: danger/danger@master
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
