name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - master
      - development
    types:
      - completed
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  DOCKER_IMAGE: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2.3.2
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - uses: nimblehq/branch-tag-action@v1.1
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Set HEROKU_APP
        run: |
          if [[ $BRANCH_TAG = "latest" ]]
          then
            echo "::set-env name=HEROKU_APP::nimble-survey-web"
          else
            echo "::set-env name=HEROKU_APP::nimble-survey-web-staging"
          fi

      - name: Docker login
        run: echo "$DOCKER_TOKEN" | docker login $DOCKER_REGISTRY --username=$DOCKER_USERNAME --password-stdin

      - name: Docker build
        run: |
          bin/docker-prepare
          docker-compose build
          docker-compose push web

      - name: Heroku login
        run: heroku container:login

      - name: Heroku release
        run: |
          heroku container:push --arg DOCKER_REGISTRY=$DOCKER_REGISTRY,DOCKER_IMAGE=$DOCKER_IMAGE,BRANCH_TAG=$BRANCH_TAG --recursive
          heroku container:release web worker
