name: Docker build test

on: push

jobs:
  docker_production_test:
    name: Docker production test
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/branch-tag

      - name: Docker build production
        run: |
          bin/docker-prepare
          docker-compose build
