name: Docker build test

on:
  push:
    branches-ignore:
      - master
      - development

jobs:
  docker_production_test:
    name: Docker production test
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_IMAGE: ${{ github.repository }}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2.3.4

      - uses: nimblehq/branch-tag-action@v1.2

      - name: Docker build production
        run: |
          bin/docker-prepare
          docker-compose build
